# Generated by Django 3.2.3 on 2021-05-20 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='id',
            new_name='comment_id',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='id',
            new_name='todo_id',
        ),
    ]
